In [1]:
#import library and the data that is going to be analysed

import pandas as pd
import seaborn as sns

df = pd.read_csv('TWO_CENTURIES_OF_UM_RACES.csv')

C:\Users\Usuario\AppData\Local\Temp\ipykernel_8024\1860427432.py:6: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('TWO_CENTURIES_OF_UM_RACES.csv')

In [2]:
#identify data that it been imported
df.shape

(7461195, 13)

In [3]:
df.dtypes

Year of event                  int64
Event dates                   object
Event name                    object
Event distance/length         object
Event number of finishers      int64
Athlete performance           object
Athlete club                  object
Athlete country               object
Athlete year of birth        float64
Athlete gender                object
Athlete age category          object
Athlete average speed         object
Athlete ID                     int64
dtype: object

In [4]:
df.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
5,2018,06.01.2018,Selva Costera (CHI),50km,22,6:25:01 h,NaN,ARG,1974.0,M,M40,7.792,5
6,2018,06.01.2018,Selva Costera (CHI),50km,22,6:28:00 h,Los Patagones,ARG,1979.0,F,W35,7.732,6
7,2018,06.01.2018,Selva Costera (CHI),50km,22,6:32:24 h,Reaktiva Chile,CHI,1967.0,F,W50,7.645,7
8,2018,06.01.2018,Selva Costera (CHI),50km,22,6:39:08 h,Puro Trail Osorno,CHI,1985.0,M,M23,7.516,8
9,2018,06.01.2018,Selva Costera (CHI),50km,22,6:45:11 h,Marlene Flores Team,CHI,1976.0,M,M40,7.404,9

In [12]:
#combining 50km and 50mi with isin
df[df['Event distance/length'].isin(['50km','50mi']) & (df['Year of event'] == 2022)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
3138208,2022,12.03.2022,Bel Monte 50 Mile Endurance Run (USA),50mi,49,7:53:36 h,"*Boston, MA",USA,1994.0,M,M23,10.194,839364
3138209,2022,12.03.2022,Bel Monte 50 Mile Endurance Run (USA),50mi,49,8:14:24 h,"*Charlotte, NC",USA,1990.0,M,M23,9.765,366598
3138210,2022,12.03.2022,Bel Monte 50 Mile Endurance Run (USA),50mi,49,8:19:16 h,"*Kannapolis, NC",USA,1979.0,M,M40,9.67,553476
3138211,2022,12.03.2022,Bel Monte 50 Mile Endurance Run (USA),50mi,49,8:23:49 h,"*Raleigh, NC",USA,1994.0,M,M23,9.583,807555
3138212,2022,12.03.2022,Bel Monte 50 Mile Endurance Run (USA),50mi,49,8:41:37 h,"*Washington, DC",USA,1997.0,M,M23,9.256,947348
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3609801,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:16:08 h,"*Peachtree City, GA",USA,1968.0,M,M50,7.141,1044739
3609802,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:27:05 h,"*Newport, PA",USA,1959.0,M,M60,7.027,50971
3609803,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:46:34 h,"*Flemington, NJ",USA,1955.0,F,W65,6.833,73152
3609804,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,11:55:29 h,"*Arlington, VA",USA,1965.0,M,M55,6.748,970133
3609805,2022,16.10.2022,Tussey Mountainback 50 Miler (USA),50mi,35,12:14:15 h,"*Johnstown, PA",USA,1981.0,F,W40,6.575,723380

In [ ]:
df[df['Event name'] == -+
   +96374]